Repository hisptz/tracker-report-app, pull requests merged in 2018-10, with the labels that each got.

#5 Add store configuration
  package-lock.json
  package.json
  src/App.js
  src/actions/simpleAction.js
  src/index.js
  src/reducers/rootReducer.js
  src/reducers/simpleReducer.js
  src/store.js
Labels: NOT FOR MERGE

#7 Fixed #1: Added configuration of store
  package-lock.json
  src/App.js
  src/actions/simpleAction.js
  src/index.js
  src/reducers/rootReducer.js
  src/reducers/simpleReducer.js
  src/store.js
Labels: LGTM

#16 add pull_request_template.md
  pull_request_template.md
Labels: LGTM

#20 [WIP] Fix #14: Fix failing tests and modify store configuration.
  .babelrc
  package.json
  src/App.js
  src/App.test.js
  src/__test__/App.test.js
  src/__test__/entry.test.js
  src/actions/simpleAction.js
  src/index.js
  src/logo.svg
  src/reducers/rootReducer.js
  src/reducers/simpleReducer.js
  src/store.js
  src/store/actions/entry.actions.js
  src/store/actions/index.js
  src/store/epics/entry.epics.js
  src/store/epics/index.js
  src/store/index.js
  src/store/reducers/entry.reducers.js
  src/store/reducers/index.js
  yarn.lock
Labels: DO NOT MERGE

#27 [WIP]: Added Initial UI structure
  .babelrc
  .codeclimate.yml
  .eslintignore
  .flowconfig
  config/env.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/paths.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  config/webpackDevServer.config.js
  package.json
  public/manifest.webapp
  scripts/build.js
  scripts/start.js
  scripts/test.js
  src/App.js
  src/components/App.css
  src/components/App.js
  src/components/HeaderBar/index.js
  src/components/__test__/App.test.js
  src/components/__test__/HeaderBar.test.js
  src/helpers/__test__/helpers.test.js
  src/helpers/helper.components.js
  src/helpers/helper.constants.js
  src/helpers/index.js
  src/index.css
  src/index.js
  src/setupProxy.js
  yarn.lock
Labels: DO NOT MERGE
